Repository LUDevNet/lu-explorer, pull requests merged in 2021-09, with the labels that each got.

#63 Basic reverse link / index infrastructure
  src/app/util/services/lu-core-data.service.ts
Labels: enhancement

#64 skills/behaviors: Only use a single HTTP request
  src/app/skills/behavior-detail-alt/behavior-detail-alt.component.css
  src/app/skills/behavior-detail-alt/behavior-detail-alt.component.html
  src/app/skills/behavior-detail-alt/behavior-detail-alt.component.ts
Labels: enhancement, D-datasource

#66 What's cool!
  src/app/objects/objects-routing.module.ts
  src/app/objects/objects.component.html
  src/app/objects/objects.module.ts
  src/app/objects/whats-cool-items/whats-cool-items.component.css
  src/app/objects/whats-cool-items/whats-cool-items.component.html
  src/app/objects/whats-cool-items/whats-cool-items.component.spec.ts
  src/app/objects/whats-cool-items/whats-cool-items.component.ts
  src/app/util/services/lu-core-data.service.ts
Labels: enhancement

#67 Misc: News & tips (What's cool)
  src/app/cdclient.ts
  src/app/misc/misc-routing.module.ts
  src/app/misc/misc.component.html
  src/app/misc/misc.module.ts
  src/app/misc/news-and-tips/news-and-tips.component.css
  src/app/misc/news-and-tips/news-and-tips.component.html
  src/app/misc/news-and-tips/news-and-tips.component.spec.ts
  src/app/misc/news-and-tips/news-and-tips.component.ts
  src/app/objects/whats-cool-items/whats-cool-items.component.html
  src/app/util/pipes/data.pipe.ts
  src/app/util/util.module.ts
Labels: T-enhancement, S-waiting-on-merge

#69 Objects: Reward Codes
  src/app/cdclient.ts
  src/app/objects/objects-routing.module.ts
  src/app/objects/objects.component.html
  src/app/objects/objects.module.ts
  src/app/objects/reward-codes/reward-codes.component.css
  src/app/objects/reward-codes/reward-codes.component.html
  src/app/objects/reward-codes/reward-codes.component.spec.ts
  src/app/objects/reward-codes/reward-codes.component.ts
Labels: T-enhancement, S-waiting-on-merge

#68 Misc: Add Level Reward
  src/app/cdclient.ts
  src/app/gui/buff/buff.component.css
  src/app/gui/buff/buff.component.html
  src/app/gui/buff/buff.component.spec.ts
  src/app/gui/buff/buff.component.ts
  src/app/gui/gui.module.ts
  src/app/misc/level-rewards/level-rewards.component.css
  src/app/misc/level-rewards/level-rewards.component.html
  src/app/misc/level-rewards/level-rewards.component.spec.ts
  src/app/misc/level-rewards/level-rewards.component.ts
  src/app/misc/misc-routing.module.ts
  src/app/misc/misc.component.html
  src/app/misc/misc.module.ts
  src/app/objects/components/skill-component/skill-component.component.css
  src/app/objects/components/skill-component/skill-component.component.html
Labels: T-enhancement, S-waiting-on-merge

#71 Add Mission component
  src/app/gui/gui.module.ts
  src/app/gui/mission/mission.component.css
  src/app/gui/mission/mission.component.html
  src/app/gui/mission/mission.component.spec.ts
  src/app/gui/mission/mission.component.ts
  src/app/gui/mission/mission.directive.spec.ts
  src/app/gui/mission/mission.directive.ts
  src/app/missions/by-subtype/by-subtype.component.css
  src/app/missions/by-subtype/by-subtype.component.html
  src/app/missions/by-type/by-type.component.css
  src/app/missions/by-type/by-type.component.html
  src/app/missions/detail/detail.component.css
  src/app/missions/detail/detail.component.html
  src/app/missions/ref-list/ref-list.component.css
  src/app/missions/ref-list/ref-list.component.html
  src/app/util/icon/icon.component.ts
  src/app/util/pipes/conditions.pipe.ts
Labels: T-enhancement, S-waiting-on-impl
